# Generated by Django 3.2.9 on 2021-11-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    #Defining fields
    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('idnumber', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('schoolyear', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('major', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('SC', 'Science'), ('LAW', 'Law'), ('NUR', 'Nursing'), ('UND', 'Undecided')], max_length=3)),
                ('gpa', models.FloatField(blank=True, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
